name: Deploy UCR dataset
on:
  push:
    tags:
      - 'ucr-v*'

jobs:
  build_docs:
    name: Deploy repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'

      - name: Build data bundles
        run: |
          pip install -U pip
          pip install -r requirements.txt
          mkdir bundles
          CB_DATASET_FILE=dataset.zip CB_RESULT_DIR=default python create_bundle.py
          CB_DATASET_FILE=dataset.zip CB_RESULT_DIR=no-missing CB_NO_MISSING=1 python create_bundle.py
          zip bundles/default.zip -r --junk-paths default/
          zip bundles/no-missing.zip -r --junk-paths no-missing/
          sha1sum bundles/default.zip | cut -d " " -f 1 > bundles/default.sha1
          sha1sum bundles/no-missing.zip | cut -d " " -f 1 > bundles/no-missing.sha1

      - uses: alexellis/upload-assets@0.2.3
        name: Upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./bundles/*"]'